### ISSUE TITLE
Cloud / Telegram issue?

### ISSUE THREAD

**Issue by balazsraacz** [abuharsky/BBQer#6]
Hi Alexander,

not sure if this project is still open or used by anyone. Despite all my efforts I can't get the communication with telegram working and getting errors with the python file as well.

 "python3 bbqcontroller.py" 
I get the following error:
"root@orangepilite:~/BBQer/cloudClient# python3 bbqcontroller.py
Traceback (most recent call last):
  File "bbqcontroller.py", line 10, in <module>
    config.read('/root/BBQer/cloudClient/configuration.txt')
  File "/usr/lib/python3.5/configparser.py", line 696, in read
    self._read(fp, filename)
  File "/usr/lib/python3.5/configparser.py", line 1077, in _read
    raise MissingSectionHeaderError(fpname, lineno, line)
configparser.MissingSectionHeaderError: File contains no section headers.
file: '/root/BBQer/cloudClient/configuration.txt', line: 1
'\ufeff[arduino]\n'
"

Either way appreciate the help

**Comment by balazsraacz** [comment]
The solution to run the script seems to have been the config file it pulled in was in the root rather than the correct in home.
